# Use Maven to build the application
FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory
WORKDIR /RentingBackendHost

# Copy the project files to the working directory
COPY . .

# Build the project and package it into a jar file
RUN mvn clean package -DskipTests

# Use an official OpenJDK runtime as a parent image
FROM openjdk:17.0.1-jdk-slim

# Set the working directory
WORKDIR /RentingBackendHost

# Copy the jar file from the build stage
COPY --from=build /RentingBackendHost/target/target/MYSQL-Driver-With-Spring-Boot-0.0.1-SNAPSHOT.jar RentingBackendHost.jar

# Expose the port the application will run on
EXPOSE 8000

# Run the jar file
ENTRYPOINT ["java", "-jar", "RentingBackendHost.jar"]

